steps:
    - imports:
        align: global

    - language_pragmas:
        style: vertical
        remove_redundant: true

    - records: {}

    - tabs:
        spaces: 4

    - trailing_whitespace: {}

columns: 80
